import assert from "node:assert/strict";
import { test } from "node:test";
import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, writeFileSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { execFileSync, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

test("reuse by mapping, derived media, revision changes, missing assets, and unknown subjects", () => {
  const root = mkdtempSync(join(tmpdir(), "coreq-inspect-"));
  const cli = join(dirname(fileURLToPath(import.meta.url)), "inspect-set.mjs");
  const write = (path, value) => { mkdirSync(dirname(join(root, path)), { recursive: true }); const bytes = JSON.stringify(value) + "\n"; writeFileSync(join(root, path), bytes); return createHash("sha256").update(bytes).digest("hex"); };
  write("plans/curriculum/curriculum.json", { revision_scheme: "canonical", questions: [{ question_id: "exam-accounting-002", number: "002", subject: "accounting", title: "test", foundation_ids: ["shared"], application_video: { episode_id: "problem-002" } }], foundations: [{ id: "shared", title: "shared", existing_video: { episode_id: "base-071", limitations: "Review applicability" } }] });
  const base = { id: "base-071", topic: { working_title: "base" } };
  const baseRevision = write("episodes/base-071/episode.json", base);
  write("episodes/problem-002/episode.json", { id: "problem-002", topic: { working_title: "problem" } });
  const short = { id: "short-002", topic: { working_title: "short" }, derivation: { kind: "short", source_episode_id: base.id, source_revision: baseRevision } };
  const revision = write("episodes/short-002/episode.json", short);
  write(".studio/runs/job-a/job.json", { id: "job-a", episodeId: short.id, mode: "all", status: "succeeded", revision, createdAt: "2026-01-01" });
  write(".studio/runs/job-a/episodes/short-002/episode.json", short);
  write(".studio/runs/job-a/episodes/short-002/output/video.mp4", "fixture");
  const inspect = () => JSON.parse(execFileSync(process.execPath, [cli, root, "exam-accounting-002"], { encoding: "utf8" }));
  const initial = inspect();
  assert(initial.episodes.some(e => e.episode_id === "base-071" && e.role === "foundation_candidate"));
  const find = data => data.episodes.find(e => e.episode_id === short.id);
  assert.equal(find(initial).video.state, "generated_current");
  assert.equal(find(initial).video.human_review, "pending");
  write(".studio/reviews/short-002.json", { job_id: "old-job", revision });
  assert.equal(find(inspect()).video.human_review, "pending");
  write("episodes/base-071/episode.json", { ...base, updated: true });
  assert.equal(find(inspect()).derivation_source.current, false);
  write("episodes/short-002/episode.json", { ...short, updated: true });
  assert.equal(find(inspect()).video.state, "stale_or_mismatched");
  unlinkSync(join(root, ".studio/runs/job-a/episodes/short-002/output/video.mp4"));
  assert.equal(find(inspect()).video.state, "missing_asset");
  const unknown = spawnSync(process.execPath, [cli, root, "exam-economics-002"], { encoding: "utf8" });
  assert.notEqual(unknown.status, 0);
  assert(unknown.stderr.includes("Question not found"));
});
